// Fallback joke list for when API is unavailable
export const fallbackJokes = [
  "Yo mama so fat, she has her own zip code.",
  "Yo mama so old, her birth certificate says 'expired'.",
  "Yo mama so poor, she can't afford the 'D' in HBO.",
  "Yo mama so stupid, she took a job at an M&M factory and got fired for throwing out the Ws.",
  "Yo mama so ugly, even her teeth go out of town for the weekend.",
  "Yo mama so fat, when she wears a yellow raincoat, people run after her yelling 'taxi'.",
  "Yo mama so lazy, she thinks a two-course meal is a couch and the refrigerator.",
  "Yo mama so hairy, you almost mistook her for Bigfoot.",
  "Yo mama so dark, when she went to night school, she got marked absent.",
  "Yo mama so sick, when she sneezed, we all had to get shots.",
  "Yo mama so big, when she gets on the scale, it says 'to be continued'.",
  "Yo mama so short, you can see her feet on her driver's license photo.",
  "Yo mama so broke, she can't even afford a dollar menu.",
  "Yo mama so dumb, she thinks Taco Bell is a phone company.",
  "Yo mama so ugly, she went to a haunted house and they paid her to leave.",
  "Yo mama so fat, she can't tie her own shoes.",
  "Yo mama so old, she knew Burger King when he was still a prince.",
  "Yo mama so poor, instead of a doorbell, she has a knocker.",
  "Yo mama so fat, she waddles to the store.",
  "Yo mama so slow, it takes her two hours to watch 60 Minutes.",
  "Yo mama so stupid, she got locked out of her car in the library.",
  "Yo mama so stinky, she made Right Guard turn left.",
  "Yo mama so hairy, she looks like Chewbacca's sister.",
  "Yo mama so big, when she sits around the house, she REALLY sits around the house.",
  "Yo mama so old, she walked out of a museum.",
  "Yo mama so short, you can see her feet when she's standing on a phone book.",
  "Yo mama so fat, she could sell shade.",
  "Yo mama so poor, she shops at the 99 cent store for Christmas dinner.",
  "Yo mama so dumb, she put a picture of herself on a map to show people where she is from.",
  "Yo mama so ugly, they didn't give her a name, they just gave her a number.",
  "Yo mama so big, she goes to the movies and sits next to everyone.",
  "Yo mama so old, she babysitted Wilma Flintstone.",
  "Yo mama so stupid, she makes Paris Hilton look like Stephen Hawking.",
  "Yo mama so broke, she shops at the thrift store's thrift store.",
  "Yo mama so fat, she has a different zip code for each butt cheek.",
  "Yo mama so lazy, she thinks a remote control is a job.",
  "Yo mama so ugly, her portrait hangs in a museum labeled 'Why?'.",
  "Yo mama so old, she used to babysit the Grand Canyon.",
  "Yo mama so poor, she went to McDonald's and asked for the 'free water'.",
  "Yo mama so dumb, she sold her car for gas money.",
  "Yo mama so fat, she's on both sides of the family.",
  "Yo mama so short, she has to take a ladder to get into a normal car.",
  "Yo mama so sick, the only cure is a hickory stick.",
  "Yo mama so hairy, I don't know whether to comb her hair or ride her.",
  "Yo mama so ugly, she'd have to sneak up on a glass of water.",
  "Yo mama so poor, she can't even afford to pay attention.",
  "Yo mama so old, she knew the Dead Sea when it was only sick.",
  "Yo mama so dumb, she put 'stop' on her resume.",
  "Yo mama so fat, when she went to the beach, Greenpeace tried to drag her back to the water.",
];
